<h2 style="text-align:center; color:#1f77b4;">
CLEANING OF THE DATASET
</h2>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("amazon.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: object(16)
memory usage: 183.3+ KB

In [3]:
df[['discounted_price', 'actual_price', 'discount_percentage', 'rating', 'rating_count']].head(10)

  discounted_price actual_price discount_percentage rating rating_count
0             ₹399       ₹1,099                 64%    4.2       24,269
1             ₹199         ₹349                 43%    4.0       43,994
2             ₹199       ₹1,899                 90%    3.9        7,928
3             ₹329         ₹699                 53%    4.2       94,363
4             ₹154         ₹399                 61%    4.2       16,905
5             ₹149       ₹1,000                 85%    3.9       24,871
6          ₹176.63         ₹499                 65%    4.1       15,188
7             ₹229         ₹299                 23%    4.3       30,411
8             ₹499         ₹999                 50%    4.2     1,79,691
9             ₹199         ₹299                 33%    4.0       43,994

In [4]:
df['discounted_price'] = (
    df['discounted_price']
    .str.replace('₹', '', regex = False)
    .str.replace(',', '', regex = False)
    .astype(float)
)
df['discounted_price'].head(10)

0    399.00
1    199.00
2    199.00
3    329.00
4    154.00
5    149.00
6    176.63
7    229.00
8    499.00
9    199.00
Name: discounted_price, dtype: float64

In [5]:
df['actual_price'] = (
    df['actual_price']
    .str.replace('₹', '', regex = False)
    .str.replace(',', '', regex = False)
    .astype(float)
)
df['actual_price'].head(10)

0    1099.0
1     349.0
2    1899.0
3     699.0
4     399.0
5    1000.0
6     499.0
7     299.0
8     999.0
9     299.0
Name: actual_price, dtype: float64

In [6]:
df['discount_percentage'] = (
    df['discount_percentage']
    .str.replace('%', '', regex = False)
    .astype(float)
)
df['discount_percentage'].head(10)

0    64.0
1    43.0
2    90.0
3    53.0
4    61.0
5    85.0
6    65.0
7    23.0
8    50.0
9    33.0
Name: discount_percentage, dtype: float64

In [7]:
df['rating'].value_counts().head(10)

rating
4.1    244
4.3    230
4.2    228
4.0    129
3.9    123
4.4    123
3.8     86
4.5     75
4       52
3.7     42
Name: count, dtype: int64

In [8]:
df['rating'].unique()

array(['4.2', '4.0', '3.9', '4.1', '4.3', '4.4', '4.5', '3.7', '3.3',
       '3.6', '3.4', '3.8', '3.5', '4.6', '3.2', '5.0', '4.7', '3.0',
       '2.8', '4', '3.1', '4.8', '2.3', '|', '2', '3', '2.6', '2.9'],
      dtype=object)

In [9]:
df['rating'] = pd.to_numeric(df['rating'], errors = 'coerce')
df['rating'].head()

0    4.2
1    4.0
2    3.9
3    4.2
4    4.2
Name: rating, dtype: float64

In [10]:
df['rating_count'].head(10)

0      24,269
1      43,994
2       7,928
3      94,363
4      16,905
5      24,871
6      15,188
7      30,411
8    1,79,691
9      43,994
Name: rating_count, dtype: object

In [11]:
df['rating_count'] = (df['rating_count'].str.replace(',', '', regex = False))
df['rating_count'] = pd.to_numeric(df['rating_count'], errors = 'coerce')
df['rating_count'].head(10)

0     24269.0
1     43994.0
2      7928.0
3     94363.0
4     16905.0
5     24871.0
6     15188.0
7     30411.0
8    179691.0
9     43994.0
Name: rating_count, dtype: float64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   float64
 4   actual_price         1465 non-null   float64
 5   discount_percentage  1465 non-null   float64
 6   rating               1464 non-null   float64
 7   rating_count         1463 non-null   float64
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: float64(5), object(11)
memory usage: 183.3+ KB

In [13]:
df[['rating', 'rating_count']].isna().sum()

rating          1
rating_count    2
dtype: int64

In [14]:
cols_to_drop = ['img_link', 'product_link', 'review_content', 'review_title', 'review_id', 'user_id', 'user_name']
df = df.drop(columns = cols_to_drop)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   float64
 4   actual_price         1465 non-null   float64
 5   discount_percentage  1465 non-null   float64
 6   rating               1464 non-null   float64
 7   rating_count         1463 non-null   float64
 8   about_product        1465 non-null   object
dtypes: float64(5), object(4)
memory usage: 103.1+ KB

In [15]:
df.isna().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 1
rating_count           2
about_product          0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(77)

In [17]:
df['product_id'].duplicated().sum()

np.int64(114)

In [18]:
df = df.drop_duplicates()
df = df.drop_duplicates(subset = 'product_id')
df.duplicated().sum()
df['product_id'].duplicated().sum()

np.int64(0)

In [19]:
df.shape

(1351, 9)

<h2 style="text-align:center; color:#1f77b4;">
EXPLORATORY DATA ANALYSIS (EDA)
</h2>

In [21]:
df.describe()

,discounted_price,actual_price,discount_percentage,rating,rating_count
count,1351.000000,1351.000000,1351.000000,1350.000000,1349.000000
mean,3304.801754,5691.176625,46.685418,4.091852,17644.494440
std,7173.975455,11218.666235,21.632611,0.297444,42145.645569
min,39.000000,39.000000,0.000000,2.000000,2.000000
25%,349.000000,899.000000,31.000000,3.900000,1106.000000
50%,899.000000,1795.000000,49.000000,4.100000,4740.000000
75%,2174.000000,4575.000000,62.000000,4.300000,16020.000000
max,77990.000000,139900.000000,94.000000,5.000000,426973.000000

In [22]:
df['category'].value_counts().head(10)

category
Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables                        161
Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones                                      68
Electronics|WearableTechnology|SmartWatches                                                               62
Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions                                             60
Electronics|Headphones,Earbuds&Accessories|Headphones|In-Ear                                              51
Electronics|HomeTheater,TV&Video|Accessories|RemoteControls                                               49
Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|MixerGrinders                                  27
Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|DryIrons     24
Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Mice                            24
Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|InstantWaterHeaters                          23
Name: count, dtype: int64

In [23]:
df[['actual_price', 'discounted_price', 'discount_percentage']].describe()

        actual_price  discounted_price  discount_percentage
count    1351.000000       1351.000000          1351.000000
mean     5691.176625       3304.801754            46.685418
std     11218.666235       7173.975455            21.632611
min        39.000000         39.000000             0.000000
25%       899.000000        349.000000            31.000000
50%      1795.000000        899.000000            49.000000
75%      4575.000000       2174.000000            62.000000
max    139900.000000      77990.000000            94.000000

In [24]:
df[['rating', 'rating_count']].describe()

            rating   rating_count
count  1350.000000    1349.000000
mean      4.091852   17644.494440
std       0.297444   42145.645569
min       2.000000       2.000000
25%       3.900000    1106.000000
50%       4.100000    4740.000000
75%       4.300000   16020.000000
max       5.000000  426973.000000

In [25]:
df[['rating', 'discount_percentage']].corr()

                       rating  discount_percentage
rating               1.000000            -0.161799
discount_percentage -0.161799             1.000000